export type StatusName =
    | "PARSE_ERROR"
    | "BAD_REQUEST"
    | "INTERNAL_SERVER_ERROR"
    | "UNAUTHORIZED"
    | "FORBIDDEN"
    | "NOT_FOUND"
    | "METHOD_NOT_SUPPORTED"
    | "TIMEOUT"
    | "CONFLICT"
    | "PRECONDITION_FAILED"
    | "PAYLOAD_TOO_LARGE"
    | "TOO_MANY_REQUESTS"
    | "CLIENT_CLOSED_REQUEST";

export const StatusCode: {
    PARSE_ERROR: "PARSE_ERROR";
    BAD_REQUEST: "BAD_REQUEST";
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR";
    UNAUTHORIZED: "UNAUTHORIZED";
    FORBIDDEN: "FORBIDDEN";
    NOT_FOUND: "NOT_FOUND";
    METHOD_NOT_SUPPORTED: "METHOD_NOT_SUPPORTED";
    TIMEOUT: "TIMEOUT";
    CONFLICT: "CONFLICT";
    PRECONDITION_FAILED: "PRECONDITION_FAILED";
    PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE";
    TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS";
    CLIENT_CLOSED_REQUEST: "CLIENT_CLOSED_REQUEST";
} = {
    PARSE_ERROR: "PARSE_ERROR",
    BAD_REQUEST: "BAD_REQUEST",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",
    NOT_FOUND: "NOT_FOUND",
    METHOD_NOT_SUPPORTED: "METHOD_NOT_SUPPORTED",
    TIMEOUT: "TIMEOUT",
    CONFLICT: "CONFLICT",
    PRECONDITION_FAILED: "PRECONDITION_FAILED",
    PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",
    TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
    CLIENT_CLOSED_REQUEST: "CLIENT_CLOSED_REQUEST",
};
